version: "3.9"

services:
  itqan:
    build: .
    container_name: itqan
    ports:
      - "8099:80"
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /tmp
